# Generated by Django 3.1.7 on 2021-04-19 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210418_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 53, 28, 298959, tzinfo=utc)),
        ),
    ]
