# Generated by Django 3.1.7 on 2021-04-15 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='follow',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
