# Generated by Django 3.1.6 on 2021-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210406_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser',
            name='followers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
