# Generated by Django 3.1.7 on 2021-04-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_instagramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
