# Generated by Django 3.1.6 on 2021-04-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_instagramuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='followers',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
