# Generated by Django 3.1.7 on 2021-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210415_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
