# Generated by Django 3.1.7 on 2021-04-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210415_0245'),
        ('authentication', '0002_auto_20210415_0420'),
    ]

    operations = [
    ]
