# Generated by Django 3.1.6 on 2021-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210406_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
