# Generated by Django 3.1.7 on 2021-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20210415_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='follower',
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
