<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-04-15 23:09
=======
# Generated by Django 3.1.7 on 2021-04-15 23:15
>>>>>>> main

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photo.photo')),
            ],
        ),
    ]
