<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-04-16 16:18
=======
# Generated by Django 3.1.7 on 2021-04-16 17:28
>>>>>>> 92b1baf7e3f0501430843908a394bfd2c40104d1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photo.photo')),
            ],
        ),
    ]
