# Generated by Django 3.1.7 on 2021-04-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20210414_0427'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photo.photo'),
        ),
    ]
