# Generated by Django 3.1.7 on 2021-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
