# Generated by Django 3.1.7 on 2021-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
