# Generated by Django 3.1.7 on 2021-04-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210413_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='button',
            field=models.CharField(default='Like', max_length=50),
        ),
    ]
